Assignment02_07_He160021/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Assignment02_07_He160021.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Assignment02_07_He160021/Pages/Forbidden.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Assignment02_07_He160021.Pages
{
    public class ForbiddenModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Assignment02_07_He160021/Pages/Index.cshtml.cs
using Assignment02_07_He160021.Dtos;
using Assignment02_07_He160021.Model;
using Assignment02_07_He160021.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;

namespace Assignment02_07_He160021.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly Prn221Assignment0207Context _context;

        public IndexModel(ILogger<IndexModel> logger, Prn221Assignment0207Context context)
        {
            _logger = logger;
            _context = context;
        }

        private List<string> SearchBys = new List<string>() { "ID", "Product Name", "Unit Price" };

        public List<Product> Products { get; set; }
        [BindProperty]
        public string FilterBy { get; set; }
        [BindProperty]
        public string SearchValue { get; set; }

        public void OnGet()
        {
            Products = _context.Products.ToList();
            ViewData["SearchBy"] = new SelectList(SearchBys);
        }

        public void OnPost()
        {
            if(SearchValue == null)
            {
                Products = _context.Products.ToList();
            }
            else
            {
                switch(FilterBy)
                {
                    case "ID":
                        Products = _context.Products
                            .Where(product => product.ProductId.ToString().Equals(SearchValue))
                            .ToList();
                        break;
                    case "Product Name":
                        Products = _context.Products
                            .Where(product => product.ProductName.Contains(SearchValue))
                            .ToList();
                        break;
                    case "Unit Price":
                        Products = _context.Products
                            .Where(product => product.UnitPrice <= decimal.Parse(SearchValue))
                            .ToList();
                        break;
                }
            }
            ViewData["SearchBy"] = new SelectList(SearchBys);
        }

        public IActionResult OnPostAddItem(IFormCollection form)
        {
            var user = HttpContext.User;
            if (user.Identity.IsAuthenticated == false)
            {
                return RedirectToPage("/Login");
            }
            string? cookie = Request.Cookies["my-cart"];
            if(cookie == null)
            {
                cookie = form["id"] + ",1";
            }
            else
            {
                Cart cart = new Cart()
                {
                    Id = int.Parse(form["id"]),
                    Number = 1
                };
                cookie = CartUltil.AddItemToCart(cart, cookie);

            }

            CookieOptions options = new CookieOptions();
            options.Expires = DateTime.Now.AddDays(30);
            Response.Cookies.Append("my-cart", cookie, options);
            return RedirectToPage("/Index");
        }
    }
}

Assignment02_07_He160021/Pages/Login.cshtml.cs
using Assignment02_07_He160021.Model;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;

namespace Assignment02_07_He160021.Pages
{
    public class UserRequest
    {
        [Required(ErrorMessage = "Username is required!")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Password is required!")]
        public string Password { get; set; }
    }

    public class LoginModel : PageModel
    {
        private readonly Prn221Assignment0207Context _context;

        public LoginModel(Prn221Assignment0207Context context)
        {
            _context = context;
        }

        [BindProperty]
        public UserRequest UserRequest { get; set; }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                Customer? customer = _context.Customers.SingleOrDefault(
                    x => x.Username == UserRequest.Username && x.Password == UserRequest.Password
                    );
                if (customer == null)
                {
                    ModelState.AddModelError("Error", "Wrong username or password.");
                    return Page();
                }
                else
                {
                    var claims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.NameIdentifier, customer.Username),
                        new Claim("Role", customer.Type.ToString())
                    };

                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    var authProperties = new AuthenticationProperties
                    {
                        AllowRefresh = true,
                        IsPersistent = true
                    };

                    await HttpContext.SignInAsync(
                            CookieAuthenticationDefaults.AuthenticationScheme,
                            new ClaimsPrincipal(claimsIdentity),
                            authProperties
                            );

                    return RedirectToPage("./Index");
                }
            }
            return Page();
        }
    }
}

Assignment02_07_He160021/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Assignment02_07_He160021.Pages
{
    public class LogoutModel : PageModel
    {
        public async Task<IActionResult> OnPostAsync()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToPage("/Index");
        }
    }
}

Assignment02_07_He160021/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Assignment02_07_He160021.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Assignment02_07_He160021/Pages/Profile.cshtml.cs
using Assignment02_07_He160021.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace Assignment02_07_He160021.Pages
{
    [Authorize]
    public class ProfileModel : PageModel
    {
        private readonly Prn221Assignment0207Context _context;

        public ProfileModel(Prn221Assignment0207Context context)
        {
            _context = context;
        }

        [BindProperty]
        public Customer Customer { get; set; } = default!;

        public void OnGet()
        {
            var user = HttpContext.User;
            var username = user.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            Customer = _context.Customers.SingleOrDefault(x => x.Username == username);
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            _context.Attach(Customer).State = EntityState.Modified;
            _context.SaveChanges();
            ModelState.AddModelError("Error", "Update success.");
            return Page();
        }
    }
}

Assignment02_07_He160021/Pages/Register.cshtml.cs
using Assignment02_07_He160021.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Assignment02_07_He160021.Pages
{
    public class RegisterModel : PageModel
    {
        private readonly Prn221Assignment0207Context _context;

        public RegisterModel(Prn221Assignment0207Context context)
        {
            _context = context;
        }

        [BindProperty]
        public Customer Customer { get; set; }

        public void OnGet()
        {
            Customer = new Customer() { Type = 0 };
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid || _context.Customers == null || Customer == null)
            {
                return Page();
            }
            if (IsUsernameExist(Customer.Username))
            {
                ModelState.AddModelError("Error", "Username is already exist!");
                return Page();
            }
            else
            {
                _context.Customers.Add(Customer);
                _context.SaveChanges();
                string message = "Register success. Please login to order product.";
                return RedirectToPage("/Login", new {message});
            }
        }

        private bool IsUsernameExist(string username)
        {
            Customer? customer = _context.Customers.SingleOrDefault(x => x.Username == username);
            return customer != null;
        }
    }
}

Assignment02_07_He160021/Pages/Forbidden.cshtml
@page
@model Assignment02_07_He160021.Pages.ForbiddenModel
@{
}


<div style="color: red;">Access Denied!</div>

Assignment02_07_He160021/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome @User.Claims.FirstOrDefault()?.Value</h1>
</div>

<form method="post">
    <div class="container row g-3 align-items-center">
        <div class="col-4">
            <input class="form-control" style="width: 350px" asp-for="SearchValue" placeholder="Input search value" />
        </div>
        <div class="col-auto">
            <select class="form-control" asp-for="FilterBy" asp-items="ViewBag.SearchBy"></select>
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-secondary">Search</button>
        </div>
    </div>

</form>

<div class="container">
    <div class="row">
        @foreach(var item in Model.Products)
        {
            <div class="col-sm-4 mt-3">
                <div class="card">
                    <img src="@item.ProductImage" class="card-img-top" style="height: 220px" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">@item.ProductName</h5>
                        <p class="card-text text-danger">$ @item.UnitPrice</p>
                        <button type="button" class="btn btn-primary" onclick="handleAddToCart(@item.ProductId)">Add To Card</button>
                        <a asp-page="./Products/Details" asp-route-id="@item.ProductId" class="btn btn-danger">View Details</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<form method="post" id="formAddToCart" asp-page-handler="AddItem" hidden>
    <input name="id" id="productId" />
</form>

<script>
    const urlParams = new URLSearchParams(window.location.search);
    const message = urlParams.get('message');
    if (message) {
        window.alert(message)
    }

    const handleAddToCart = (productId) => {
        document.getElementById('productId').value = productId;
        document.getElementById('formAddToCart').submit();
    }
</script>

Assignment02_07_He160021/Pages/Login.cshtml
@page
@model Assignment02_07_He160021.Pages.LoginModel
@{
}

<form method="post" style="width: 500px">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="UserRequest.Username" ></label>
        <input type="text" class="form-control" asp-for="UserRequest.Username" placeholder="Enter Username">
        <span asp-validation-for="UserRequest.Username" class="text-danger"></span>
    </div>
    <div class="form-group mt-3">
        <label asp-for="UserRequest.Password" ></label>
        <input type="password" class="form-control" asp-for="UserRequest.Password" placeholder="Password">
        <span asp-validation-for="UserRequest.Username" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-secondary mt-3" style="width: 150px">Login</button>
</form>

<div>
    <a asp-page="/Register">Register account</a>
</div>

<script>
    const urlParams = new URLSearchParams(window.location.search);
    const message = urlParams.get('message');
    if(message){
        window.alert(message)
    }
</script>

Assignment02_07_He160021/Pages/Logout.cshtml
@page
@model Assignment02_07_He160021.Pages.LogoutModel
@{
}

Assignment02_07_He160021/Pages/Profile.cshtml
@page
@model Assignment02_07_He160021.Pages.ProfileModel
@{
}

<h1>Profile</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="Customer.CustomerId" />
            <input type="hidden" asp-for="Customer.Type" />
            <div class="form-group">
                <label asp-for="Customer.Username" class="control-label"></label>
                <input asp-for="Customer.Username" class="form-control" readonly/>
                <span asp-validation-for="Customer.Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer.Password" class="control-label"></label>
                <input asp-for="Customer.Password" class="form-control" />
                <span asp-validation-for="Customer.Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer.FullName" class="control-label"></label>
                <input asp-for="Customer.FullName" class="form-control" />
                <span asp-validation-for="Customer.FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer.Address" class="control-label"></label>
                <input asp-for="Customer.Address" class="form-control" />
                <span asp-validation-for="Customer.Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer.Phone" class="control-label"></label>
                <input asp-for="Customer.Phone" class="form-control" />
                <span asp-validation-for="Customer.Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="/Index">Back to home</a>
</div>

Assignment02_07_He160021/Pages/Register.cshtml
@page
@model Assignment02_07_He160021.Pages.RegisterModel
@{
}

<h1>Register</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Customer.Username" class="control-label"></label>
                <input asp-for="Customer.Username" class="form-control" />
                <span asp-validation-for="Customer.Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer.Password" class="control-label"></label>
                <input asp-for="Customer.Password" class="form-control" />
                <span asp-validation-for="Customer.Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer.FullName" class="control-label"></label>
                <input asp-for="Customer.FullName" class="form-control" />
                <span asp-validation-for="Customer.FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer.Address" class="control-label"></label>
                <input asp-for="Customer.Address" class="form-control" />
                <span asp-validation-for="Customer.Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer.Phone" class="control-label"></label>
                <input asp-for="Customer.Phone" class="form-control" />
                <span asp-validation-for="Customer.Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Register" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="/Login">Back to Login</a>
</div>