Assignment02_07_He160021/Pages/Carts/Cart.cshtml.cs
using Assignment02_07_He160021.Dtos;
using Assignment02_07_He160021.Model;
using Assignment02_07_He160021.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Net;
using System.Security.Claims;

namespace Assignment02_07_He160021.Pages
{
    [Authorize]
    public class CartModel : PageModel
    {
        private readonly Prn221Assignment0207Context _context;

        public CartModel(Prn221Assignment0207Context context)
        {
            _context = context;
        }

        public List<Cart> Carts { get; set; }
        public decimal TotalPrice { get; set; }
        [BindProperty]
        public string Address { get; set; }
        [BindProperty]
        public string Phone { get; set; }

        public void OnGet()
        {
            List<Cart> list = GetListItemInCart();
            Carts = list;
            TotalPrice = list.ConvertAll(x => x.Number * x.Product.UnitPrice).Sum();

            Customer? customer = GetUserLoggedIn();
            Address = customer.Address;
            Phone = customer.Phone;
        }

        public IActionResult OnPostRemovItem(IFormCollection form)
        {
            Cart cart = new Cart() { Id = int.Parse(form["id"]) };
            string? cookie = Request.Cookies["my-cart"];
            string newCookie = CartUltil.RemoveItem(cart, cookie);
            if(string.IsNullOrEmpty(newCookie))
            {
                Response.Cookies.Delete("my-cart");
            }
            else
            {
                UpdateCookie(newCookie);
            }
            return RedirectToPage("/Carts/Cart");
        }

        public IActionResult OnPostChangeNumber(IFormCollection form)
        {
            Cart cart = new Cart() 
            {
                Id = int.Parse(form["id"]),
                Number = int.Parse(form["number"])
            };
            if(cart.Number <= 0)
            {
                string message = "Numbers of product should more than 0.";
                return RedirectToPage("/Carts/Cart", new { message });
            }
            if(!CheckNumberInStore(cart))
            {
                string message = "Numbers of this product is not enough.";
                return RedirectToPage("/Carts/Cart", new { message });
            }
            string? cookie = Request.Cookies["my-cart"];
            string newCookie = CartUltil.ChangeNumber(cart, cookie);
            UpdateCookie(newCookie);
            return RedirectToPage("/Carts/Cart");
        }

        public IActionResult OnPostCheckOut()
        {
            Customer? customer = GetUserLoggedIn();

            if (customer != null)
            {
                Order order = new Order()
                {
                    CustomerId = customer.CustomerId,
                    OrderDate = DateTime.Now,
                    ShipAddress = customer.Address
                };
                _context.Orders.Add(order);
                _context.SaveChanges();

                int addedOrderId = order.OrderId;

                List<Cart> list = GetListItemInCart();

                foreach (Cart cart in list)
                {
                    OrderDetail orderDetail = new OrderDetail()
                    {
                        OrderId = addedOrderId,
                        ProductId = cart.Id,
                        UnitPrice = cart.Product.UnitPrice,
                        Quantity = cart.Number
                    };
                    Product product = cart.Product;
                    product.QuantityPerUnit = product.QuantityPerUnit - cart.Number;
                    _context.OrderDetails.Add(orderDetail);
                    _context.Attach(product).State = EntityState.Modified;
                }

                _context.SaveChanges();

                Response.Cookies.Delete("my-cart");
                string message = "Order success!";
                return RedirectToPage("/Index", new {message});
            }
            return Page();
        }

        private bool CheckNumberInStore(Cart cart)
        {
            Product? product = _context.Products.SingleOrDefault(x => x.ProductId == cart.Id);
            return product.QuantityPerUnit >= cart.Number;
        }

        private void UpdateCookie(string cookie)
        {
            CookieOptions options = new CookieOptions();
            options.Expires = DateTime.Now.AddDays(30);
            Response.Cookies.Append("my-cart", cookie, options);
        }

        private List<Cart> GetListItemInCart()
        {
            List<Cart> list = new List<Cart>();
            string? cookie = Request.Cookies["my-cart"];
            if (cookie != null)
            {
                list = CartUltil.GetCartInfo(cookie);
                foreach (var cart in list)
                {
                    cart.Product = _context.Products.FirstOrDefault(x => x.ProductId == cart.Id);
                }
            }
            return list;
        }

        private Customer? GetUserLoggedIn()
        {
            var user = HttpContext.User;
            var username = user.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            return _context.Customers.SingleOrDefault(x => x.Username == username);
        }
    }
}

Assignment02_07_He160021/Pages/Carts/Cart.cshtml
@page
@model Assignment02_07_He160021.Pages.CartModel
@{
}

<section class="h-100 h-custom" style="background-color: #d2c9ff;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12">
                <div class="card card-registration card-registration-2" style="border-radius: 15px;">
                    <div class="card-body p-0">
                        <div class="row g-0">
                            <div class="col-lg-8">
                                <div class="p-5">
                                    <div class="d-flex justify-content-between align-items-center mb-5">
                                        <h1 class="fw-bold mb-0 text-black">Shopping Cart</h1>
                                        <h6 class="mb-0 text-muted">@(Model.Carts == null ? 0 : Model.Carts.Count) items</h6>
                                    </div>
                                    <hr class="my-4">
                                    
                                    @if(Model.Carts != null)
                                    {
                                        foreach(var item in Model.Carts)
                                        {
                                            <div class="row mb-4 d-flex justify-content-between align-items-center">
                                            <div class="col-md-2 col-lg-2 col-xl-2">
                                                <img src="@item.Product?.ProductImage"
                                                 class="img-fluid rounded-3" alt="Cotton T-shirt">
                                            </div>
                                            <div class="col-md-3 col-lg-3 col-xl-3">
                                                <h6 class="text-muted">@item.Product?.ProductName</h6>
                                            </div>
                                            <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                                                <button class="btn btn-link px-2"
                                                    onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                                                    <i class="fas fa-minus"></i>
                                                </button>

                                                <input id="form1" min="0" name="quantity" value="@item.Number" type="number"
                                                   class="form-control form-control-sm" onchange="handleChangeNumber(event, @item.Id)" />

                                                <button class="btn btn-link px-2"
                                                    onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                                                    <i class="fas fa-plus"></i>
                                                </button>
                                            </div>
                                            <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                                <h6 class="mb-0">$ @item.Product?.UnitPrice</h6>
                                            </div>
                                            <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                                                <a href="#!" class="text-muted" onclick="handleRemoveItem(@item.Id)">x</a>
                                            </div>
                                        </div>

                                        <hr class="my-4">
                                        }
                                    }
                                    else
                                    {
                                        <h3>Cart is empty.</h3>
                                    }

                                    <div class="pt-5">
                                        <h6 class="mb-0">
                                            <a asp-page="/Index" class="text-body">
                                                <i class="fas fa-long-arrow-alt-left me-2"></i>Back to shop
                                            </a>
                                        </h6>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 bg-grey">
                                <div class="p-5">
                                    <h3 class="fw-bold mb-5 mt-2 pt-1">Summary</h3>
                                    <hr class="my-4">

                                    <div class="d-flex justify-content-between mb-4">
                                        <h5 class="text-uppercase">items @(Model.Carts == null ? 0 : Model.Carts.Count)</h5>
                                        <h5>$ @Model.TotalPrice</h5>
                                    </div>

                                    <div class="d-flex justify-content-between mb-4">
                                        <h5 class="text-uppercase">Shipping</h5>
                                        <h5>$ 0.00</h5>
                                    </div>

                                    <h5 class="text-uppercase mb-3">Phone number</h5>

                                    <div class="mb-5">
                                        <div class="form-outline">
                                            <input type="text" asp-for="Phone" class="form-control form-control-lg" />
                                        </div>
                                    </div>

                                    <h5 class="text-uppercase mb-3">Address</h5>

                                    <div class="mb-5">
                                        <div class="form-outline">
                                            <input type="text" asp-for="Address" class="form-control form-control-lg" />
                                        </div>
                                    </div>

                                    <hr class="my-4">

                                    <div class="d-flex justify-content-between mb-5">
                                        <h5 class="text-uppercase">Total price</h5>
                                        <h5>$ @Model.TotalPrice</h5>
                                    </div>

                                    <button type="button" class="btn btn-dark btn-block btn-lg"
                                            data-mdb-ripple-color="dark" onclick="handleCheckCout()">
                                        Buy
                                    </button>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<form method="post" id="formRemoveItem" asp-page-handler="RemovItem" hidden>
    <input name="id" id="productId" />
</form>

<form method="post" id="formChangeNumber" asp-page-handler="ChangeNumber" hidden>
    <input name="id" id="deleteId" />
    <input name="number" id="number" />
</form>

<form method="post" id="formCheckOut" asp-page-handler="CheckOut" hidden>
</form>

<script>
    const urlParams = new URLSearchParams(window.location.search);
    const message = urlParams.get('message');
    if(message){
        window.alert(message)
    }

    const handleRemoveItem = (productId) => {
        document.getElementById('productId').value = productId;
        document.getElementById('formRemoveItem').submit();
    }

    const handleChangeNumber = (event, productId) => {
        const number = event.target.value;
        document.getElementById('deleteId').value = productId;
        document.getElementById('number').value = number;
        document.getElementById('formChangeNumber').submit();
    }

    const handleCheckCout = () => {
        document.getElementById('formCheckOut').submit();
    }
</script>